(function(g){var window=this;var Z5=function(a,b,c){a.w.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Gm(a.w,b,c)},uua=function(a,b){var c=[];
g.Pj(b,function(d){try{var e=g.Jn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.In(e)&&c.push(d)},a);
return c},vua=function(a,b){var c=uua(a,b);
(0,g.y)(c,function(d){g.Jn.prototype.remove.call(this,d)},a)},wua=function(a){if(a.Wc){if(a.Wc.locationOverrideToken)return{locationOverrideToken:a.Wc.locationOverrideToken};
if(null!=a.Wc.latitudeE7&&null!=a.Wc.longitudeE7)return{latitudeE7:a.Wc.latitudeE7,longitudeE7:a.Wc.longitudeE7}}return null},xua=function(a,b){g.bb(a,b)||a.push(b)},yua=function(a,b){var c=b instanceof g.Zb?b:g.dc(b,/^data:image\//i.test(b));
a.src=g.ac(c)},b6=function(){},zua=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Aua=function(a,b,c,d){var e=new g.vm(null,void 0);
a&&g.wm(e,a);b&&g.xm(e,b);c&&g.ym(e,c);d&&(e.u=d);return e},c6=function(a,b){g.vo[a]=!0;
var c=g.to();c&&c.publish.apply(c,arguments);g.vo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.rm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Bua(this,a.capabilities||""),Cua(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Bua=function(a,b){a.capabilities.clear();
(0,g.be)(b.split(","),g.Sa(g.z.contains,Dua)).forEach(function(c){a.capabilities.add(c)})},Cua=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Eua=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Fua=function(a){return new e6(a)},Gua=function(a){return g.Ma(a)?(0,g.ic)(a,Fua):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ma(a)?"["+(0,g.ic)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Hua=function(a){return(0,g.ic)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Za(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Zr)(),c=(0,g.Yr)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Iua=function(){var a=(0,g.Yr)();
a&&vua(a,a.o.lf(!0))},m6=function(){var a=g.as("yt-remote-connected-devices")||[];
g.sb(a);return a},Jua=function(a){if(g.cb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Kua=function(a){g.$r("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.as("yt-remote-device-id");a||(a=i6(),g.$r("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.bb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.bb(a,b);g.bs()&&g.ub(a,b);a=Jua(a);if(g.cb(a))try{g.mq("remote_sid")}catch(c){}else try{g.kq("remote_sid",a.join(","),-1)}catch(c){}},Lua=function(){return g.as("yt-remote-session-browser-channel")},Mua=function(){return g.as("yt-remote-local-screens")||[]},Nua=function(){g.$r("yt-remote-lounge-token-expiration",!0,86400)},Oua=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ic)(Mua(),function(d){return d.loungeToken}),c=(0,g.ic)(a,function(d){return d.loungeToken});
(0,g.ai)(c,function(d){return!g.bb(b,d)})&&Nua();
g.$r("yt-remote-local-screens",a,31536E3)},Pua=function(a,b){g.$r("yt-remote-session-browser-channel",a);
g.$r("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.bb(c,d)||c.push(d);Kua(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.fb(a,o6());Kua(a)},Qua=function(){if(!r6){var a=g.Un();
a&&(r6=new g.Dn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Rua=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Sua=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Tua(a.shift(),function(){s6(a)}):t6()},Uua=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Tua=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Sua();
a&&a(!1,"No cast extension found")},Wua=function(){if(Vua){var a=2,b=Sua(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Tua("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},Xua=function(){Wua();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.B.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Fd=b;this.B=(0,g.x)(this.mF,this);this.o=!1;this.u=0;this.w=this.Ea=null;this.A=[]},v6=function(a,b,c){g.B.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Fd=b;this.u=(0,g.x)(this.nF,this);this.o=[]},w6=function(a){a.Ea=g.zf(a.u,a.Fd);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return zua(a)},y6=function(){},z6=function(){},Yua=function(){},$ua=function(a){return(a=Zua(a))?new ActiveXObject(a):new XMLHttpRequest},Zua=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.N1(this);this.u=new g.yf;this.u.setInterval(250)},bva=function(a,b,c){a.uj=1;
a.Rg=$5(b.clone());a.Mi=c;a.C=!0;ava(a,null)},B6=function(a,b,c,d,e){a.uj=1;
a.Rg=$5(b.clone());a.Mi=null;a.C=c;e&&(a.VB=!1);ava(a,d)},ava=function(a,b){a.dk=(0,g.H)();
C6(a);a.Dh=a.Rg.clone();a6(a.Dh,"t",a.F);a.Qm=0;a.Nc=a.o.qr(a.o.Em()?b:null);0<a.Zr&&(a.Ep=new v6((0,g.x)(a.TC,a,a.Nc),a.Zr));a.A.ka(a.Nc,"readystatechange",a.eO);var c=a.ni?g.z.clone(a.ni):{};a.Mi?(a.lq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.Dh,a.lq,a.Mi,c)):(a.lq="GET",a.VB&&!g.Qd&&(c.Connection="close"),a.Nc.send(a.Dh,a.lq,null,c));a.o.bf(1)},eva=function(a,b,c){for(var d=!0;!a.Uh&&a.Qm<c.length;){var e=cva(a,c);
if(e==D6){4==b&&(a.gh=4,E6(15),d=!1);break}else if(e==dva){a.gh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.gh=1,E6(17),d=!1);a.df=a.df&&d;d||(G6(a),H6(a))},cva=function(a,b){var c=a.Qm,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return dva;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Qm=d+c;return e},gva=function(a,b){a.dk=(0,g.H)();
C6(a);var c=b?window.location.hostname:"";a.Dh=a.Rg.clone();Z5(a.Dh,"DOMAIN",c);Z5(a.Dh,"t",a.F);try{a.jf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.gh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in fva)k=I6[l]=fva[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Cc(g.Db("b/12014412"),d+"</body></html>");a.jf.open();a.jf.write(g.xc(c));a.jf.close();a.jf.parentWindow.m=(0,g.x)(a.zN,a);a.jf.parentWindow.d=(0,g.x)(a.bB,a,!0);a.jf.parentWindow.rpcClose=(0,g.x)(a.bB,a,!1);c=a.jf.createElement("DIV");a.jf.parentWindow.document.body.appendChild(c);d=g.cc(a.Dh.toString());d=g.Lc(g.ac(d));d=g.Cc(g.Db("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Dc(c,d);a.o.bf(1)},C6=function(a){a.ev=(0,g.H)()+a.B;
hva(a,a.B)},hva=function(a,b){if(null!=a.vk)throw Error("WatchDog timer not null");
a.vk=J6((0,g.x)(a.HN,a),b)},K6=function(a){a.vk&&(g.v.clearTimeout(a.vk),a.vk=null)},H6=function(a){a.o.Kx()||a.Uh||a.o.qp(a)},G6=function(a){K6(a);
g.ne(a.Ep);a.Ep=null;a.u.stop();g.vpa(a.A);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.jf&&(a.jf=null)},F6=function(a,b){try{a.o.VA(a,b),a.o.bf(4)}catch(c){}},jva=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;iva(a,b,function(k){k?c(!0):g.v.setTimeout(function(){jva(a,b,c,d,f)},f)})}},iva=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
yua(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},kva=function(a){this.o=a;
this.u=new y6},lva=function(a){var b=M6(a.o,a.Fk,"/mail/images/cleardot.gif");
$5(b);jva(b.toString(),5E3,(0,g.x)(a.hE,a),3,2E3);a.bf(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Yd=new A6(a,void 0,void 0,void 0),a.Yd.ni=a.Xr,b=a.o,b=M6(b,b.Em()?a.kl:null,a.Yr),E6(5),!g.Od||g.sd(10))a6(b,"TYPE","xmlhttp"),B6(a.Yd,b,!1,a.kl,!1);else{a6(b,"TYPE","html");var c=a.Yd;a=!!a.kl;c.uj=3;c.Rg=$5(b.clone());gva(c,a)}},P6=function(a){g.Ne.call(this);
this.headers=new g.rm;this.R=a||null;this.w=!1;this.V=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.aa=this.G=this.T=!1;this.F=0;this.J=null;this.ea="";this.M=this.Z=!1},mva=function(a){return g.Od&&g.rd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},nva=function(a){return"content-type"==a.toLowerCase()},pva=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;ova(a);Q6(a)},ova=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},rva=function(a){if(a.w&&"undefined"!=typeof g.S1)if(a.V[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.zf(a.RA,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Vc(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!qva.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";ova(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){sva(a);
var c=a.o,d=a.V[0]?g.Ja:null;a.o=null;a.V=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},sva=function(a){a.o&&a.M&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},tva=function(a,b){this.o=a;
this.map=b;this.context=null},uva=function(a){g.pe.call(this,"statevent",a)},vva=function(a,b){g.pe.call(this,"timingevent",a);
this.size=b},wva=function(a){g.pe.call(this,"serverreachability",a)},zva=function(a){xva(a);
if(3==a.o){var b=a.cm++,c=a.Wn.clone();Z5(c,"SID",a.w);Z5(c,"RID",b);Z5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.uj=2;b.Rg=$5(c.clone());yua(new Image,b.Rg.toString());b.dk=(0,g.H)();C6(b)}yva(a)},Ava=function(a){a.GE(1,0);
a.Wn=M6(a,null,a.Wr);W6(a)},xva=function(a){a.Vg&&(a.Vg.abort(),a.Vg=null);
a.sc&&(a.sc.cancel(),a.sc=null);a.Tf&&(g.v.clearTimeout(a.Tf),a.Tf=null);X6(a);a.Rd&&(a.Rd.cancel(),a.Rd=null);a.ah&&(g.v.clearTimeout(a.ah),a.ah=null)},Bva=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new tva(a.OJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Rd||a.ah||(a.ah=J6((0,g.x)(a.aB,a),0),a.nj=0)},Dva=function(a,b){if(1==a.o){if(!b){a.cm=Math.floor(1E5*Math.random());
var c=a.cm++,d=new A6(a,"",c,void 0);d.ni=null;var e=Y6(a),f=a.Wn.clone();Z5(f,"RID",c);Z5(f,"CVER","1");V6(a,f);bva(d,f,e);a.Rd=d;a.o=2}}else 3==a.o&&(b?Cva(a,b):0==a.u.length||a.Rd||Cva(a))},Cva=function(a,b){if(b)if(6<a.Vh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.cm-1;var d=Y6(a)}else c=b.G,d=b.Mi;else c=a.cm++,d=Y6(a);var e=a.Wn.clone();Z5(e,"SID",a.w);Z5(e,"RID",c);Z5(e,"AID",a.Gj);V6(a,e);c=new A6(a,a.w,c,a.nj+1);c.ni=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Rd=c;bva(c,e,d)},V6=function(a,b){if(a.Bd){var c=a.Bd.gx();
c&&g.z.forEach(c,function(d,e){Z5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Vh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Vh?e:f-d;try{g.z.forEach(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Eva=function(a){a.sc||a.Tf||(a.F=1,a.Tf=J6((0,g.x)(a.ZA,a),0),a.dj=0)},Z6=function(a){if(a.sc||a.Tf||3<=a.dj)return!1;
a.F++;a.Tf=J6((0,g.x)(a.ZA,a),Fva(a,a.dj));a.dj++;return!0},N6=function(a,b,c){a.jq=c;
a.uf=b.kg;a.C||Ava(a)},X6=function(a){null!=a.ci&&(g.v.clearTimeout(a.ci),a.ci=null)},Fva=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Bd&&(c=null);var d=(0,g.x)(a.QO,a);c||(c=new g.vm("//www.google.com/images/cleardot.gif"),$5(c));iva(c.toString(),1E4,d)}else E6(2);Gva(a,b)},Gva=function(a,b){a.o=0;
a.Bd&&a.Bd.ww(b);yva(a);xva(a)},yva=function(a){a.o=0;
a.uf=-1;if(a.Bd)if(0==a.A.length&&0==a.u.length)a.Bd.gr();else{g.jb(a.A);var b=g.jb(a.u);a.A.length=0;a.u.length=0;a.Bd.gr(b)}},M6=function(a,b,c){var d=g.Dm(c);
if(""!=d.o)b&&g.xm(d,b+"."+d.o),g.ym(d,d.A);else{var e=window.location;d=Aua(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Tk&&g.z.forEach(a.Tk,function(f,k){Z5(d,k,f)});
Z5(d,"VER",a.Vh);V6(a,d);return d},J6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new uva(a7,a))},Hva=function(){},Iva=function(){this.o=[];
this.u=[]},Jva=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.B.call(this);
this.o=new g.I(this.pN,0,this);g.C(this,this.o);this.Fd=5E3;this.u=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Cn;this.u=new b7(this.tO,this);this.o=null;this.ub=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.M=c||!1},Kva=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.jq,sessionId:a.o.w,arrayId:a.o.Gj}},Lva=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Dva(a.o),zva(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Mva=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Vc(4,a))||"";b&&(this.port=":"+b);this.domain=g.Wc(a)||"";a=g.oc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Wb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.fd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.A,d,!0),onError:g.Sa(a.w,e),Wd:g.Sa(a.B,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.cq(b,a)},Qva=function(){var a=Nva;
Ova();h7.push(a);Pva(h7)},i7=function(a,b){Ova();
var c=h7,d=Rva(a,String(b));g.cb(c)?Sva(d):(Pva(c),(0,g.y)(c,function(e){e(d)}))},Ova=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",h7,void 0))},Sva=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Pva=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Rva=function(a,b){var c=((0,g.H)()-Tva)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},Uva=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Vva=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.be)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Uva(a,b[d])||c;return c},Wva=function(a,b){var c=a.o.length;
a.o=(0,g.be)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Ea=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},Xva=function(a){if(a.o.length){var b=(0,g.ic)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.xF,a),(0,g.x)(a.wF,a))}},o7=function(a){var b=Gua(Mua());
b=(0,g.be)(b,function(c){return!c.uuid});
return Vva(a,b)},q7=function(a,b){Oua((0,g.ic)(a.o,Eua));
b&&Nua()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.as("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.bb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.rk(this.o))},Yva=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(g.z.Rc(b)!=g.z.Rc(a.o))var c=!1;
else{c=g.z.Fb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.rk(a.o)),a.o=b,a.P("screenChange"));Zva(a)},u7=function(a){isNaN(a.w)||g.so(a.w);
a.w=g.qo((0,g.x)(a.uu,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},$va=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Ub("Requesting availability of screen w/o lounge token.")});
return b},Zva=function(a){a=g.z.Fb(g.z.filter(a.o,function(b){return b}));
g.sb(a);a.length?g.$r("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};awa(this)},cwa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.me();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);Yva(a.u,l,function(m){e(m?l:null)})}else c?bwa(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Yva(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},dwa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},bwa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.cq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},ewa=function(a){a.o=a.w.me();
for(var b=g.z.uC(a.B),c=0,d=a.o.length;c<d;++c){var e=a.o[c];e.uuid=b[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},awa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.GF,a));ewa(a);a.A=Gua(g.as("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.me,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.P("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.$r("yt-remote-automatic-screen-cache",(0,g.ic)(a.A,Eua)));x7(a);a.B[b.uuid]=b.id;g.$r("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.as("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.V=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.V,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.zP,this);this.B=(0,g.x)(this.PN,this);this.A=g.qo((0,g.x)(function(){fwa(this,null)},this),12E4)},gwa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.rk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.rk(b))},fwa=function(a,b){g.so(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.tp,a),d=(0,g.x)(a.pe,a);a.Cx(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.R=c;this.B=null;this.F=g.Ja;this.C=NaN;this.M=(0,g.x)(this.CP,this);this.o=g.Ja},hwa=function(a){a.o=a.H.aD(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.tp(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.pe(b)},a))},iwa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Qua()&&(b.env_useStageMdx=1);return g.dd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.qo((0,g.x)(this.Hj,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.wM,this)},jwa=function(a,b){return b?g.Za(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Nva=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.ne(a.o),(a.o=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.u):a.P("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.YA,a,b)),b.w?a.P("yt-remote-cast2-session-change",b.w):c&&a.o.Hj(null)):a.P("yt-remote-cast2-session-change",null))},kwa=function(a){var b=a.u.ZC(),c=a.o&&a.o.u;
a=(0,g.ic)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=jwa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},qwa=function(a,b,c,d,e,f,k){lwa()?mwa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?nwa(a,c):(window.__onGCastApiAvailable=function(l,m){l?nwa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),owa(),c(!1))},d?g.Co("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Xua():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(Wua(),s6(pwa.map(Uua))))):H7("Cannot initialize because not running Chrome")},owa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);rwa(!1);g.yo(M7);M7.length=0},N7=function(){return!!g.as("yt-remote-cast-installed")},swa=function(){var a=g.as("yt-remote-cast-receiver");
return a?a.friendlyName:null},twa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},uwa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.xo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},lwa=function(){var a=0<=g.oc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Us||a},vwa=function(a,b){L7().init(a,b)},mwa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.$r("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.$r("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.$r("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},nwa=function(a,b){K7(!0);
I7(!1);vwa(a,function(c){c?(rwa(!0),g.zo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),owa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.$r("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},rwa=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.J=!1;this.H=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.J=!1;a.hasNext=!1;a.F=0;a.C=(0,g.H)();a.B=0;a.u=0;a.G=0;a.H=0;a.A=NaN;a.w=!1},T7=function(a){return a.ab()?((0,g.H)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.H)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.z.Nm(a.o);b.hasPrevious=a.J;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new Iva;this.w=this.u=null;this.H=(0,g.x)(this.vK,this);this.F=(0,g.x)(this.em,this);this.G=(0,g.x)(this.uK,this);this.J=(0,g.x)(this.GK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.hv,this),wwa(this))):c=3;0!=c&&(b?this.hv(c):g.qo((0,g.x)(function(){this.hv(c)},this),0));
var d=uwa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},wwa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Sa(this.tM,b),this))},a)},xwa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){50>a.B.Rc()&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){xwa(a);
a.A.setPlayerContextData(X7(b));wwa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.em(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.em(a.w.media[0]))},ywa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Ub("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ub("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.M=!1;this.G=this.F=this.H=this.J=NaN;this.V=[];this.A=this.C=this.w=this.Sa=this.o=null;this.T=a;this.V.push(g.dp(window,"beforeunload",(0,g.x)(this.pF,this)));this.u=[];this.Sa=new R7;this.R=b.id;this.o=zwa(this,c);this.o.subscribe("handlerOpened",this.zK,this);this.o.subscribe("handlerClosed",this.wK,this);this.o.subscribe("handlerError",this.xK,this);this.o.subscribe("handlerMessage",this.yK,this);Mva(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Sa.videoId;
g.bs()&&g.$r("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},zwa=function(a,b){return new c7(f7(a.T,"/bc"),b)},h8=function(a,b){a.P("proxyStateChange",b)},Awa=function(a){a.B=g.qo((0,g.x)(function(){g8("Connecting timeout");
this.kj(1)},a),2E4)},i8=function(a){g.so(a.B);
a.B=NaN},j8=function(a){g.so(a.J);
a.J=NaN},Bwa=function(a){k8(a);
a.H=g.qo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.so(a.H);
a.H=NaN},Dwa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Ax()&&a.Sa.reset(),h8(a,1),l8(a,"getNowPlaying"),Cwa(a)):a.kj(1)},Ewa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.z.isEmpty(b.params)?a.Sa.o=null:a.Sa.o=b.params,a.P("remotePlayerChange"))},Fwa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;W7(a.Sa,c,d);a.P("remoteQueueChange")},Hwa=function(a,b){b.params=b.params||{};
Fwa(a,b);Gwa(a,b);a.P("autoplayDismissed")},Gwa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Sa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Sa.G=isNaN(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Sa.playerState?Bwa(a):k8(a);a.P("remotePlayerChange")},Iwa=function(a,b){if(-1E3!=
a.Sa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Sa,isNaN(c)?0:c);a.P("remotePlayerChange")}},Jwa=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=parseInt(b.params.volume,10);a.Sa.muted=c;a.P("remotePlayerChange")},Kwa=function(a,b){a.C=b.params.videoId;
a.P("nowAutoplaying",parseInt(b.params.timeout,10))},Lwa=function(a,b){var c="true"==b.params.hasNext;
a.Sa.J="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.P("previousNextChange")},Cwa=function(a){g.so(a.G);
a.G=g.qo((0,g.x)(a.kj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.rk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Ed=a;this.u=[];this.u.push(this.Ed.$_s("screenChange",(0,g.x)(this.xP,this)));this.u.push(this.Ed.$_s("onlineScreenChange",(0,g.x)(this.WL,this)))},Qwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.M("MDX_CONFIG")||b;Iua();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Qua()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",o8,void 0));Mwa();var c=p8();if(!c){var d=new v7(n8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);qwa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.rk(b)),s8.push(g.xo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.xo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.xo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.xo("yt-remote-cast2-session-change",Nwa)),s8.push(g.xo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),twa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.go("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.rk(a)),Owa(a),c.start(),q8()||Pwa())},Swa=function(){var a=Rwa();
N7()&&g.as("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Rwa=function(){var a=p8().Ed.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return Hua(a)},y8=function(){var a=Twa();
!a&&N7()&&swa()&&(a={key:"cast-selector-receiver",name:swa()});return a},Twa=function(){var a=Rwa(),b=w8();
b||(b=u8());return g.Za(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().me();return k6(b,a)},Nwa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Uwa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},Vwa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Uwa("");g.Ia("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.bs();
if(!a)return null;var b=p8().me();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Uwa(a.id);var c=new f8(n8,a,v8());c.connect(b,Vwa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Pwa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),twa(),r8("Skipping connecting because no session screen found."))},Mwa=function(){var a=v8();
if(g.z.isEmpty(a)){a=o6();var b=g.as("yt-remote-session-name")||"",c=g.as("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Owa=function(a){a?(g.$r("yt-remote-session-app",a.app),g.$r("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.B.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.C(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.sL);this.w.L(b,"captionschanged",this.tK);this.w.L(b,"captionssettingschanged",this.lC);this.w.L(b,"videoplayerreset",this.vp);this.w.L(b,"mdxautoplaycancel",this.gE);this.R=this.w.L(b,"onVolumeChange",this.DA);this.G=!1;this.o=c;c.ga();c.subscribe("proxyStateChange",this.UA,this);c.subscribe("remotePlayerChange",this.nm,this);c.subscribe("remoteQueueChange",this.vp,this);c.subscribe("autoplayUpNext",
this.rA,this);c.subscribe("previousNextChange",this.QA,this);c.subscribe("nowAutoplaying",this.MA,this);c.subscribe("autoplayDismissed",this.qA,this);this.suggestion=null;this.H=new g.sC(64);this.A=new g.I(this.jC,500,this);g.C(this,this.A);this.C=new g.I(this.kC,1E3,this);g.C(this,this.C);this.M=new u6(this.ZO,0,this);g.C(this,this.M);this.F={};this.V=new g.I(this.LC,1E3,this);g.C(this,this.V);this.J=new v6(this.eI,1E3,this);g.C(this,this.J);this.T=g.Ja;this.lC();this.vp();this.nm()},H8=function(a,
b){var c=a.B,d=a.u.getVideoData().lengthSeconds;
c.V=b||0;c.player.P("progresssync",b,d)},Wwa=function(a){H8(a,0);
a.A.stop();I8(a,new g.sC(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.z.extend(c,b));a.o.aC(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.wf,wua(c));I8(a,new g.sC(1))},Xwa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{wT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.yC(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.gS(a.u.app,d);a.H=b;Ywa(a.B,c,b)}},M8=function(){g.S.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",N:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"Voc\u00ea n\u00e3o fez login"},{D:"div",I:"ytp-mdx-popup-description",W:"Os v\u00eddeos que voc\u00ea assistir poder\u00e3o ser adicionados ao hist\u00f3rico de visualiza\u00e7\u00e3o da TV e influenciar\u00e3o as recomenda\u00e7\u00f5es dela. Para evitar isso, cancele e fa\u00e7a login no YouTube em um computador."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",
Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancelar"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"Confirmar"}]}]}]});this.u=new g.hL(this,250);g.C(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.S.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.jL()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.hL(this,250);g.C(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);Zwa(this,g.iK(a))},Zwa=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.NL("Erro em $RECEIVER_NAME",c):b.ab()||g.X(b,4)?g.NL("Reproduzindo em $RECEIVER_NAME",c):g.NL("Conectado a $RECEIVER_NAME",c);a.ia("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.HN.call(this,"Reproduzir em",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.NK.call(this,a);
this.u={key:i6(),name:"Este computador"};this.B=null;this.A=[];this.R=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.sC(64);this.V=0;this.H=-1;this.C=null;if(!g.Ty(this.player.O())){a=this.player;var b=g.XB(a);b&&(b=b.Sl())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.AK(a,b.element,4);this.C=new M8;g.C(this,this.C);g.AK(a,this.C.element,4);this.M=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},Ywa=function(a,b,
c){a.F=c;
a.player.P("presentingplayerstatechange",new g.DC(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.T(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.M||!a.C);if(c?0:g.az(a.player.O())||"WEB_EMBEDDED_PLAYER"==a.player.O().deviceParams.c)g.iK(a.player).ab()?a.player.pauseVideo():(a.G=(0,g.x)(a.TN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.Zb(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=
c.videoId;if(!d&&!e||(2==a.player.getAppState()||1==a.player.getAppState())&&g.T(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.wf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=wua(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.rk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().me(),(c=k6(c,b.key))&&A8(c,1))}},fva={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},$wa={},Dua={aQ:"atp",GS:"ska",vS:"que",PR:"mus",FS:"sus",bR:"dsp",CS:"seq"};
d6.prototype.ai=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
d6.prototype.qb=function(a){return a?this.id==a.id:!1};
var r6,n6="",Vua=Rua("loadCastFramework")||Rua("loadCastApplicationFramework"),pwa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(u6,g.B);g.h=u6.prototype;g.h.lF=function(a){this.A=arguments;this.o=!1;this.Ea?this.w=(0,g.H)()+this.Fd:this.Ea=g.zf(this.B,this.Fd)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Eb.X.call(this)};
g.h.mF=function(){this.w?(this.Ea=g.zf(this.B,this.w-(0,g.H)()),this.w=null):(this.Ea=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Ua(v6,g.B);g.h=v6.prototype;g.h.tj=!1;g.h.jl=0;g.h.Ea=null;g.h.Jx=function(a){this.o=arguments;this.Ea||this.jl?this.tj=!0:w6(this)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null,this.tj=!1,this.o=[])};
g.h.pause=function(){this.jl++};
g.h.resume=function(){this.jl--;this.jl||!this.tj||this.Ea||(this.tj=!1,w6(this))};
g.h.X=function(){v6.Eb.X.call(this);this.stop()};
g.h.nF=function(){this.Ea=null;this.tj&&!this.jl&&(this.tj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Zua(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ua(Yua,z6);S8=new Yua;g.h=A6.prototype;g.h.ni=null;g.h.df=!1;g.h.vk=null;g.h.ev=null;g.h.dk=null;g.h.uj=null;g.h.Rg=null;g.h.Dh=null;g.h.Mi=null;g.h.Nc=null;g.h.Qm=0;g.h.jf=null;g.h.lq=null;g.h.gh=null;g.h.ll=-1;g.h.VB=!0;g.h.Uh=!1;g.h.Zr=0;g.h.Ep=null;var dva={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.eO=function(a){a=a.target;var b=this.Ep;b&&3==R6(a)?b.Jx():this.TC(a)};
g.h.TC=function(a){try{if(a==this.Nc)a:{var b=R6(this.Nc),c=this.Nc.C,d=this.Nc.getStatus();if(g.Od&&!g.sd(10)||g.Qd&&!g.rd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.eh&&!T6(this.Nc))break a;this.Uh||4!=b||7==c||(8==c||0>=d?this.o.bf(3):this.o.bf(2));K6(this);var e=this.Nc.getStatus();this.ll=e;var f=T6(this.Nc);(this.df=200==e)?(4==b&&G6(this),this.C?(eva(this,b,f),g.eh&&this.df&&3==b&&(this.A.ka(this.u,"tick",this.XN),this.u.start())):F6(this,f),this.df&&!this.Uh&&(4==b?this.o.qp(this):(this.df=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.gh=3,E6(13)):(this.gh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Nc&&T6(this.Nc)}finally{}};
g.h.XN=function(){var a=R6(this.Nc),b=T6(this.Nc);this.Qm<b.length&&(K6(this),eva(this,a,b),this.df&&4!=a&&C6(this))};
g.h.zN=function(a){J6((0,g.x)(this.yN,this,a),0)};
g.h.yN=function(a){this.Uh||(K6(this),F6(this,a),C6(this))};
g.h.bB=function(a){J6((0,g.x)(this.xN,this,a),0)};
g.h.xN=function(a){this.Uh||(G6(this),this.df=a,this.o.qp(this),this.o.bf(4))};
g.h.cancel=function(){this.Uh=!0;G6(this)};
g.h.HN=function(){this.vk=null;var a=(0,g.H)();0<=a-this.ev?(2!=this.uj&&this.o.bf(3),G6(this),this.gh=2,E6(18),H6(this)):hva(this,this.ev-a)};
g.h.getLastError=function(){return this.gh};g.h=kva.prototype;g.h.Xr=null;g.h.Yd=null;g.h.Fp=!1;g.h.Lx=null;g.h.Tn=null;g.h.Ks=null;g.h.Yr=null;g.h.Be=null;g.h.kg=-1;g.h.kl=null;g.h.Fk=null;g.h.connect=function(a){this.Yr=a;a=M6(this.o,null,this.Yr);E6(3);this.Lx=(0,g.H)();var b=this.o.G;null!=b?(this.kl=b[0],(this.Fk=b[1])?(this.Be=1,lva(this)):(this.Be=2,O6(this))):(a6(a,"MODE","init"),this.Yd=new A6(this,void 0,void 0,void 0),this.Yd.ni=this.Xr,B6(this.Yd,a,!1,null,!0),this.Be=0)};
g.h.hE=function(a){if(a)this.Be=2,O6(this);else{E6(4);var b=this.o;b.uf=b.Vg.kg;$6(b,9)}a&&this.bf(2)};
g.h.qr=function(a){return this.o.qr(a)};
g.h.abort=function(){this.Yd&&(this.Yd.cancel(),this.Yd=null);this.kg=-1};
g.h.Kx=function(){return!1};
g.h.VA=function(a,b){this.kg=a.ll;if(0==this.Be)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.uf=this.kg;$6(c,2);return}this.kl=c[0];this.Fk=c[1]}else c=this.o,c.uf=this.kg,$6(c,2);else if(2==this.Be)if(this.Fp)E6(7),this.Ks=(0,g.H)();else if("11111"==b){if(E6(6),this.Fp=!0,this.Tn=(0,g.H)(),c=this.Tn-this.Lx,!g.Od||g.sd(10)||500>c)this.kg=200,this.Yd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Tn=this.Ks=(0,g.H)(),this.Fp=!1};
g.h.qp=function(){this.kg=this.Yd.ll;if(this.Yd.df)0==this.Be?this.Fk?(this.Be=1,lva(this)):(this.Be=2,O6(this)):2==this.Be&&((!g.Od||g.sd(10)?!this.Fp:200>this.Ks-this.Tn)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.Be?E6(9):2==this.Be&&E6(10);var a=this.o;this.Yd.getLastError();a.uf=this.kg;$6(a,2)}};
g.h.Em=function(){return this.o.Em()};
g.h.isActive=function(){return this.o.isActive()};
g.h.bf=function(a){this.o.bf(a)};g.Ua(P6,g.Ne);var qva=/^https?$/i,axa=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.T=!1;this.w=!0;this.o=this.R?$ua(this.R):$ua(S8);this.V=this.R?this.R.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.RA,this);try{b6(S6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));pva(this,f);return}a=
c||"";var e=this.headers.clone();d&&g.um(d,function(f,k){e.set(k,f)});
d=g.Za(e.Fb(),nva);c=g.v.FormData&&a instanceof g.v.FormData;!g.bb(axa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{sva(this),0<this.F&&(this.M=mva(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.M)),this.M?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Mx,this)):this.J=g.zf(this.Mx,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),pva(this,f)}};
g.h.Mx=function(){"undefined"!=typeof g.S1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Eb.X.call(this)};
g.h.RA=function(){this.ga()||(this.aa||this.G||this.B?rva(this):this.vM())};
g.h.vM=function(){rva(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Tk=null;g.h.Rd=null;g.h.sc=null;g.h.Wr=null;g.h.Wn=null;g.h.iw=null;g.h.lo=null;g.h.cm=0;g.h.OJ=0;g.h.Bd=null;g.h.ah=null;g.h.Tf=null;g.h.ci=null;g.h.Vg=null;g.h.jq=null;g.h.Gj=-1;g.h.uy=-1;g.h.uf=-1;g.h.nj=0;g.h.dj=0;g.h.Vh=8;var a7=new g.Ne;g.Ua(uva,g.pe);g.Ua(vva,g.pe);g.Ua(wva,g.pe);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Wr=b;this.Tk=c||{};d&&void 0!==e&&(this.Tk.OSID=d,this.Tk.OAID=e);this.C?(J6((0,g.x)(this.Dw,this,a),100),Ava(this)):this.Dw(a)};
g.h.Dw=function(a){this.Vg=new kva(this);this.Vg.Xr=null;this.Vg.u=this.B;this.Vg.connect(a)};
g.h.Kx=function(){return 0==this.o};
g.h.aB=function(a){this.ah=null;Dva(this,a)};
g.h.ZA=function(){this.Tf=null;this.sc=new A6(this,this.w,"rpc",this.F);this.sc.ni=null;this.sc.Zr=0;var a=this.iw.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.w);Z5(a,"CI",this.jq?"0":"1");Z5(a,"AID",this.Gj);V6(this,a);if(!g.Od||g.sd(10))Z5(a,"TYPE","xmlhttp"),B6(this.sc,a,!0,this.lo,!1);else{Z5(a,"TYPE","html");var b=this.sc,c=!!this.lo;b.uj=3;b.Rg=$5(a.clone());gva(b,c)}};
g.h.VA=function(a,b){if(0!=this.o&&(this.sc==a||this.Rd==a))if(this.uf=a.ll,this.Rd==a&&3==this.o)if(7<this.Vh){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Tf){if(this.sc)if(this.sc.dk+3E3<this.Rd.dk)X6(this),this.sc.cancel(),this.sc=null;else break a;Z6(this);E6(19)}}else this.uy=c[1],0<this.uy-this.Gj&&37500>c[2]&&this.jq&&0==this.dj&&!this.ci&&(this.ci=J6((0,g.x)(this.pK,this),6E3));else $6(this,11)}else b!=$wa.xQ.o&&$6(this,11);else if(this.sc==
a&&X6(this),!g.Lb(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Gj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.lo=e[2],e=e[3],null!=e?this.Vh=e:this.Vh=6,this.o=3,this.Bd&&this.Bd.yw(),this.iw=M6(this,this.Em()?this.lo:null,this.Wr),Eva(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Bd&&this.Bd.xw(e),this.dj=0)}}};
g.h.pK=function(){null!=this.ci&&(this.ci=null,this.sc.cancel(),this.sc=null,Z6(this),E6(20))};
g.h.qp=function(a){if(this.sc==a){X6(this);this.sc=null;var b=2}else if(this.Rd==a)this.Rd=null,b=1;else return;this.uf=a.ll;if(0!=this.o)if(a.df)1==b?(b=(0,g.H)()-a.dk,a7.dispatchEvent(new vva(a7,a.Mi?a.Mi.length:0,b,this.nj)),W6(this),this.A.length=0):Eva(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.uf)){if(d=1==b)this.Rd||this.ah||1==this.o||2<=this.nj?d=!1:(this.ah=J6((0,g.x)(this.aB,this,a),Fva(this,this.nj)),this.nj++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.GE=function(a){if(!g.bb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.QO=function(a){a?E6(2):(E6(1),Gva(this,8))};
g.h.qr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Z=!1;return a};
g.h.isActive=function(){return!!this.Bd&&this.Bd.isActive(this)};
g.h.bf=function(a){a7.dispatchEvent(new wva(a7,a))};
g.h.Em=function(){return!(!g.Od||g.sd(10))};
g.h=Hva.prototype;g.h.yw=function(){};
g.h.xw=function(){};
g.h.ww=function(){};
g.h.gr=function(){};
g.h.gx=function(){return{}};
g.h.isActive=function(){return!0};g.h=Iva.prototype;g.h.Rc=function(){return this.o.length+this.u.length};
g.h.isEmpty=function(){return g.cb(this.o)&&g.cb(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.bb(this.o,a)||g.bb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Apa)(b,a);0<=c?(g.eb(b,c),b=!0):b=!1;return b||g.fb(this.u,a)};
g.h.tc=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(b7,g.B);g.h=b7.prototype;g.h.pN=function(){this.Fd=Math.min(3E5,2*this.Fd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Fd+15E3*Math.random();g.dn(this.o,a);this.u=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Fd=5E3};g.Ua(c7,Hva);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.uh=function(a){return this.w.oi(a)};
g.h.P=function(a,b){return this.w.P.apply(this.w,arguments)};
g.h.dispose=function(){this.ub||(this.ub=!0,g.ne(this.w),Lva(this),g.ne(this.u),this.u=null)};
g.h.ga=function(){return this.ub};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Bd=null);d.Bd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Gj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.z.extend(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Bva(this.o,c)};
g.h.yw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Bva(this.o,a[b])}this.P("handlerOpened")};
g.h.ww=function(a){var b=2==a&&401==this.o.uf;4==a||b||this.u.start();this.P("handlerError",a)};
g.h.gr=function(a){if(!this.u.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.gx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.z.extend(a,this.B);return a};
g.h.xw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),zva(this.o)):this.P("handlerMessage",new Jva(a[0],a[1]))};
g.h.tO=function(){this.u.isActive();var a=this.o,b=0;a.sc&&b++;a.Rd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Tva=(0,g.H)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ua(m7,g.Q);m7.prototype.me=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ea)&&this.YC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ea)||(g.so(this.Ea),this.Ea=NaN)};
g.h.X=function(){this.stop();g.Q.prototype.X.call(this)};
g.h.YC=function(){this.Ea=NaN;this.o=g.cq(f7(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.vP,this),onError:(0,g.x)(this.uP,this),Wd:(0,g.x)(this.wP,this)})};
g.h.vP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.P("pairingComplete",new e6(c))};
g.h.uP=function(a){this.o=null;a.status&&404==a.status?this.u>=bxa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=bxa[this.u],this.Ea=g.qo((0,g.x)(this.YC,this),a),this.u++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.wP=function(){this.o=null;this.P("pairingFailed",Error("Server not responding"))};
var bxa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.P("screenChange");!g.as("yt-remote-lounge-token-expiration")&&Xva(this);g.so(this.u);this.u=g.qo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Uva(this,a);q7(this,!1);this.P("screenChange");b(a);a.token||Xva(this)};
g.h.remove=function(a,b){var c=o7(this);Wva(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.hq=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.X=function(){g.so(this.u);p7.Eb.X.call(this)};
g.h.xF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.wF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.as("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?u7(this):(this.A=(0,g.H)()+3E5,g.$r("yt-remote-fast-check-period",this.A),this.uu())};
g.h.isEmpty=function(){return g.z.isEmpty(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.z.filter(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.so(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.X.call(this)};
g.h.uu=function(){g.so(this.w);this.w=NaN;this.u&&this.u.abort();var a=$va(this);if(g.z.Rc(a)){var b=f7(this.B,"/pairing/get_screen_availability"),c={lounge_token:g.z.Fb(a).join(",")};this.u=g7(this.B,b,c,(0,g.x)(this.TM,this,a),(0,g.x)(this.SM,this))}else t7(this,{}),u7(this)};
g.h.TM=function(a,b){this.u=null;var c=g.z.Fb($va(this));if(g.tb(c,g.z.Fb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Ub("Changing Screen set during request."),this.uu()};
g.h.SM=function(a){this.Ub("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Ub=function(a){i7("OnlineScreenService",a)};g.Ua(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.P("screenChange"),this.u.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.hq=function(a,b,c,d){this.w.contains(a)?this.w.hq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.me=function(a){return a?this.o:g.ib(this.o,(0,g.be)(this.A,function(b){return!this.contains(b)},this))};
g.h.ZC=function(){return(0,g.be)(this.me(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.aD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.ne(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.ne(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.yP=function(a,b,c,d){g.cq(f7(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||dwa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);dwa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Wd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.ne(this.w);g.ne(this.u);v7.Eb.X.call(this)};
g.h.GF=function(){ewa(this);this.P("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ua(y7,g.Q);g.h=y7.prototype;g.h.tp=function(a){this.w=a;this.P("sessionScreen",this.w)};
g.h.pe=function(a){this.ga()||(a&&z7(this,""+a),this.w=null,this.P("sessionScreen",null))};
g.h.info=function(a){i7(this.V,a)};
g.h.cD=function(){return null};
g.h.Du=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Du("");y7.Eb.X.call(this)};g.Ua(A7,y7);g.h=A7.prototype;g.h.Cu=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);gwa(this)};
g.h.Hj=function(a){this.info("launchWithParams no-op for Cast: "+g.rk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.pe()},this),(0,g.x)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.h.Du=g.Ja;g.h.X=function(){this.info("disposeInternal");g.so(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Eb.X.call(this)};
g.h.PN=function(a,b){if(!this.ga())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.rk(c));switch(d){case "mdxSessionStatus":fwa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.Cx=function(a,b,c,d){cwa(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.qo((0,g.x)(this.Cx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.cD=function(){return this.o};
g.h.zP=function(a){this.ga()||a||(z7(this,"Cast session died."),this.pe())};g.Ua(B7,y7);g.h=B7.prototype;g.h.Cu=function(a){this.A=a;this.A.addUpdateListener(this.M)};
g.h.Hj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ja;g.so(this.C);this.A?this.A.stop((0,g.x)(this.pe,this,null),(0,g.x)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.h.X=function(){this.o();this.o=g.Ja;g.so(this.C);this.A&&this.A.removeUpdateListener(this.M);this.A=null;B7.Eb.X.call(this)};
g.h.CP=function(a){this.ga()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.pe())};
g.h.ts=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,iwa(this));a(b);hwa(this)}else this.F=(0,g.x)(function(){g.so(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,iwa(this));a(c);hwa(this)},this),this.C=g.qo((0,g.x)(function(){this.F()},this),100)};
g.h.ZF=function(a,b,c){cwa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.tp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.ts(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.ts(b,c)},this))};g.Ua(C7,y7);C7.prototype.stop=function(){this.pe()};
C7.prototype.Cu=g.Ja;C7.prototype.Hj=function(){g.so(this.o);this.o=NaN;var a=k6(this.H.me(),this.u.label);a?this.tp(a):this.pe(Error("No such screen"))};
C7.prototype.X=function(){g.so(this.o);this.o=NaN;C7.Eb.X.call(this)};g.Ua(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.AM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.XA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.OK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.A),Qva(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.bD,this)),this.w=kwa(this),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(k){this.Ub("Failed to set initial custom receivers: "+g.rk(k))},this)),this.P("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Ub("Failed to initialize API: "+g.rk(k));
b(!1)},this))};
g.h.BO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.me(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=jwa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ja,(0,g.x)(function(e){this.Ub("Failed to set initial custom receivers: "+g.rk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.Du(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.CO=function(a){this.ga()?this.Ub("Setting connection data on disposed cast v2"):this.o?this.o.Hj(a):this.Ub("Setting connection data without a session")};
g.h.BP=function(){this.ga()?this.Ub("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.XA,this),(0,g.x)(this.XM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.bD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Nva,b=g.w("yt.mdx.remote.debug.handlers_");g.fb(b||[],a);g.ne(this.o);D7.Eb.X.call(this)};
g.h.Ub=function(a){i7("Controller",a)};
g.h.YA=function(a,b){this.o==a&&(b||G7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.wM=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.P("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Ub("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Ub("Stopping receiver w/o session: "+a.friendlyName)}else this.Ub("onReceiverAction_ called without receiver.")};
g.h.OK=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ub("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Ub("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ub('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.ZF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.ts,b))};
g.h.XA=function(a){if(!this.ga()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Ub("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.me(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ne(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.YA,this,this.o)),this.o.Hj(null));this.o.Cu(a)}}};
g.h.AP=function(){return this.o?this.o.cD():null};
g.h.XM=function(a){this.ga()||(this.Ub("Failed to estabilish a session: "+g.rk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.AM=function(a){E7("Receiver availability updated: "+a);if(!this.ga()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.P("yt-remote-cast2-availability-change",F7(this))}};
g.h.bD=function(){this.ga()||(this.w=kwa(this),E7("Updating custom receivers: "+g.rk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(){this.Ub("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.CO;D7.prototype.setConnectedScreenStatus=D7.prototype.BO;D7.prototype.stopSession=D7.prototype.BP;D7.prototype.getCastSession=D7.prototype.AP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.h=R7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.J=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.A=a.liveIngestionTime,this.w=!isNaN(this.A))};
g.h.ab=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.w?this.G+T7(this):this.G};
g.h.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ab()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.P("remotePlayerChange")}else a8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.P("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Ub("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Ub("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Sa(this.setVolume,a,b))};
g.h.aC=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.rk(b.style),g.z.extend(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Sa(this.aC,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.rk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.XC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Sa(this.XC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Sa(this.nextVideo,a,b))};
g.h.Mw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Mw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.P("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.X=function(){xwa(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.X.call(this)};
g.h.hv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.cb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.tM=function(a,b){this.P(a,b)};
g.h.vK=function(a){if(!a)this.em(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.em=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),ywa(this),this.P("remotePlayerChange")};
g.h.uK=function(a){a?(ywa(this),this.P("remotePlayerChange")):this.em(null)};
g.h.GK=function(){var a=uwa();a&&Y7(this,a)};
g.h.Ub=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;U7(this.Sa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.rk(l));this.o.connect({method:"setPlaylist",
params:g.rk(l)},a,Lua())}else g8("Connecting without params"),this.o.connect({},a,Lua());Awa(this)};
g.h.dispose=function(){this.ga()||(this.P("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.so(this.F);this.F=NaN;g.so(this.G);this.G=NaN;this.w=null;g.ep(this.V);this.V.length=0;this.o.dispose();g.Q.prototype.X.call(this);this.A=this.C=this.u=this.Sa=this.o=null};
g.h.pF=function(){this.kj(2)};
g.h.zK=function(){g8("Channel opened");this.M&&(this.M=!1,j8(this),this.J=g.qo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.kj(1)},this),15E3));
Pua(Kva(this.o),this.R)};
g.h.wK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.xK=function(a){q6();isNaN(this.al())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,g8("Channel error: "+a+" with reconnection in "+this.al()+" ms"),h8(this,2))};
g.h.yK=function(a){a.params?g8("Received: action="+a.action+", params="+g.rk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.ic)(a,function(c){return new d6(c)});
a=!!g.Za(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Dwa(this,a);break;case "loungeScreenDisconnected":g.gb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Dwa(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.Za(this.u,function(c){return c.qb(b)})||xua(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.gb(this.u,function(c){return c.qb(b)});
break;case "gracefulDisconnect":break;case "playlistModified":Fwa(this,a);break;case "nowPlaying":Hwa(this,a);break;case "onStateChange":Gwa(this,a);break;case "onAdStateChange":Iwa(this,a);break;case "onVolumeChanged":Jwa(this,a);break;case "onSubtitlesTrackChanged":Ewa(this,a);break;case "nowAutoplaying":Kwa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.P("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Lwa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.pO=function(){if(this.w){var a=this.w;this.w=null;this.Sa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.eF=function(){var a=3;this.ga()||(a=0,isNaN(this.al())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.kj=function(a){g8("Disconnecting with "+a);i8(this);this.P("beforeDisconnect",a);1==a&&q6();Lva(this.o,a);this.dispose()};
g.h.dF=function(){var a=this.Sa;this.w&&(a=this.Sa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.DO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.w=b.videoId,g.so(this.F),this.F=g.qo((0,g.x)(this.pO,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&V7(this.Sa)==V7(b)&&g.rk(this.Sa.o)==g.rk(b.o)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.y)(c,function(d){this.P(d)},this)};
g.h.Ax=function(){var a=this.o.C.id,b=g.Za(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.al=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.H)():NaN};
g.h.SE=function(){return this.A||"UNSUPPORTED"};
g.h.TE=function(){return this.C||""};
g.h.tP=function(){if(!isNaN(this.al())){var a=this.o.u;g.en(a.o);a.start()}};
g.h.yO=function(a,b){l8(this,a,b);Cwa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.uh;f8.prototype.getProxyState=f8.prototype.eF;f8.prototype.disconnect=f8.prototype.kj;f8.prototype.getPlayerContextData=f8.prototype.dF;f8.prototype.setPlayerContextData=f8.prototype.DO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Ax;f8.prototype.getReconnectTimeout=f8.prototype.al;f8.prototype.getAutoplayMode=f8.prototype.SE;f8.prototype.getAutoplayVideoId=f8.prototype.TE;f8.prototype.reconnect=f8.prototype.tP;
f8.prototype.sendMessage=f8.prototype.yO;g.r(m8,m7);g.h=m8.prototype;g.h.me=function(a){return this.Ed.$_gs(a)};
g.h.contains=function(a){return!!this.Ed.$_c(a)};
g.h.get=function(a){return this.Ed.$_g(a)};
g.h.start=function(){this.Ed.$_st()};
g.h.add=function(a,b,c){this.Ed.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ed.$_r(a,b,c)};
g.h.hq=function(a,b,c,d){this.Ed.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.Ed.$_ubk(this.u[a]);this.u.length=0;this.Ed=null;m7.prototype.X.call(this)};
g.h.xP=function(){this.P("screenChange")};
g.h.WL=function(){this.P("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.yP;v7.prototype.$_gsppc=v7.prototype.aD;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.hq;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.me;v7.prototype.$_gos=v7.prototype.ZC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.uh;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.B);g.h=G8.prototype;
g.h.X=function(){g.B.prototype.X.call(this);this.A.stop();this.C.stop();this.M.stop();this.T();this.o.unsubscribe("proxyStateChange",this.UA,this);this.o.unsubscribe("remotePlayerChange",this.nm,this);this.o.unsubscribe("remoteQueueChange",this.vp,this);this.o.unsubscribe("autoplayUpNext",this.rA,this);this.o.unsubscribe("previousNextChange",this.QA,this);this.o.unsubscribe("nowAutoplaying",this.MA,this);this.o.unsubscribe("autoplayDismissed",this.qA,this);this.o=this.B=null};
g.h.pz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":$7(this.o).ab()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Jx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.tK=function(a){this.M.lF(a)};
g.h.ZO=function(a){this.pz("control_subtitles_set_track",g.z.isEmpty(a)?null:a)};
g.h.lC=function(){var a=this.u.getOption("captions","track");g.z.isEmpty(a)||K8(this,a)};
g.h.DA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.nm,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.V.start();this.o.subscribe("remotePlayerChange",this.nm,this)}};
g.h.sL=function(){g.z.isEmpty(this.F)||Xwa(this,this.F);this.G=!1};
g.h.UA=function(a,b){this.C.stop();2==b&&this.kC()};
g.h.nm=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.sC(8));this.jC();break;case 1085:case 3:I8(this,new g.sC(9));break;case 1083:case 0:I8(this,new g.sC(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.sC(4));break;case 2:I8(this,new g.sC(4));H8(this,V7(a));
break;case -1:I8(this,new g.sC(64));break;case -1E3:I8(this,new g.sC(128,{errorCode:"mdx.remoteerror",errorMessage:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,Xwa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.V.isActive()||this.LC()}else Wwa(this)};
g.h.QA=function(){this.u.P("mdxpreviousnextchange")};
g.h.vp=function(){J8(this)||Wwa(this)};
g.h.gE=function(){this.o.Mw()};
g.h.rA=function(){};
g.h.MA=function(a){isNaN(a)||this.u.P("mdxnowautoplaying",a)};
g.h.qA=function(){this.u.P("mdxautoplaycanceled")};
g.h.eI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.LC=function(){if(J8(this)){var a=$7(this.o);this.w.Va(this.R);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.R=this.w.L(this.u,"onVolumeChange",this.DA)}};
g.h.jC=function(){this.A.stop();if(!this.o.ga()){var a=$7(this.o);a.ab()&&I8(this,new g.sC(8));H8(this,V7(a));this.A.start()}};
g.h.kC=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.S);M8.prototype.Zb=function(){this.u.show()};
M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.S);N8.prototype.A=function(a){Zwa(this,a.state)};g.r(O8,g.HN);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.vb(a,this.B,this),g.JN(this,(0,g.ic)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.Fe(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.Ze=function(a){return"cast-selector-receiver"==a?"Elenco...":this.C[a].name};
O8.prototype.jd=function(a){g.HN.prototype.jd.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.Ya()};g.r(P8,g.NK);g.h=P8.prototype;
g.h.create=function(){Qwa(g.Ky(this.player.O()));this.A.push(g.xo("yt-remote-before-disconnect",this.qK,this));this.A.push(g.xo("yt-remote-connection-change",this.BM,this));this.A.push(g.xo("yt-remote-receiver-availability-change",this.SA,this));this.A.push(g.xo("yt-remote-auto-connect",this.zM,this));this.A.push(g.xo("yt-remote-receiver-resumed",this.yM,this));this.A.push(g.xo("mdx-privacy-popup-confirm",this.bO,this));this.A.push(g.xo("mdx-privacy-popup-cancel",this.aO,this));this.SA()};
g.h.load=function(){this.player.cancelPlayback();g.NK.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=Vwa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.V=a||0,this.player.P("progresssync",a,void 0));Ywa(this,this.F,this.F);g.nS(this.player.app,6)};
g.h.unload=function(){this.player.P("mdxautoplaycanceled");this.w=this.u;g.oe(this.B,this.o);this.o=this.B=null;g.NK.prototype.unload.call(this);g.nS(this.player.app,5);Q8(this)};
g.h.X=function(){g.yo(this.A);g.NK.prototype.X.call(this)};
g.h.Kl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.pz.apply(this.B,[a].concat(g.na(c)))};
g.h.getAdState=function(){return this.H};
g.h.gF=function(){return this.loaded?this.B.suggestion:null};
g.h.Oy=function(){return this.o?$7(this.o).J:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.V};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.T(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Sc():!a.isAdPlaying()&&this.player.Sc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+T7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.AG=function(){this.o&&this.o.XC()};
g.h.qK=function(a){1==a&&(this.R=this.o?$7(this.o):null)};
g.h.BM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.R=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.ne(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.R)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.P("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.SA=function(){this.J=[this.u].concat(Swa());var a=y8()||this.u;R8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.TN=function(a){!this.M&&g.FC(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.zM=function(){var a=y8();R8(this,a)};
g.h.yM=function(){this.w=y8()};
g.h.bO=function(){this.M=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.aO=function(){this.M=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Pc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.BG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Nf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.bL.remote=P8;})(_yt_player);
